### ISSUE TITLE
Vault - Using existing Vault - Wrong variable in test

### ISSUE THREAD

**Issue by gaelleescuit** [CloudTestDrive/helidon-kubernetes#20]
https://github.com/CloudTestDrive/helidon-kubernetes/blob/3be256fef8c6d1af513a0835bb2b6f325cce0245/setup/common/vault-setup.sh#L123

Replace DBNAME by VAULT_NAME or the test will fail in most cases

**Comment by atimgraves** [comment]
fixed the var name as reported by Gaelle, manually entering the name when prompted should also work. Added more error correction and recovery if the vault is setup but not the key
allow manual entry of the vault key name
