### ISSUE TITLE
Storefront and stock manager services not starting

### ISSUE THREAD

**Issue by mbtrent** [CloudTestDrive/helidon-kubernetes#23]
Creating stockmanager deployment
error: the path "stockmanager-deployment.yaml" does not exist
Creating storefront deployment
error: the path "storefront-deployment.yaml" does not exist

**Comment by vissree** [comment]
Got the same error. Looks like the template files for these deployment specs are available in the root folder
```
helidon-kubernetes/stockmanager-deployment-template.yaml
helidon-kubernetes/storefront-deployment-template.yaml
```

But not sure what to use for the `OCIR_LOCATION/OCIR_STORAGE_NAMESPACE/OCIR_REPO` placeholder.

The `helidon-kubernetes/setup/common/deployments-update.sh` script expects the values for OCIR_LOCATION, OCIR_STORAGE_NAMESPACE and OCIR_REPO as inputs.

**Comment by anarkes** [comment]
Hi, I was able to make it work after follow the following steps

IMPORTANT: You should run all the commands in the Cloud Shell

1. cd $HOME/helidon-kubernetes/setup/common
2. bash user-identity-setup.sh
3. bash auth-token-setup.sh
	if you are asked to save auth token value for later, press y and enter
4. bash ocir-setup.sh
5. bash container-image-setup.sh
	This command will take some minutes since it will create the docker image for stockmanager and storefront
6. cd $HOME/helidon-kubernetes/setup/kubernetes-labs
7. bash configureGitAndFullyInstallCluster.sh <your_initials>
        Replace <your_initials> by the initials you set when execute the Task 3: Recording your initials

**Comment by atimgraves** [comment]
this shoudl happen for you automatically. I've upgraded the scritpts and they are now a lot more end to end automated and there are now "all in one" scritps that run the whole sequence for you.
Sorry for the delays in getting back to you but I've only just noticed the issues comming up and missed the origional notifications
